# Generated by Django 2.2 on 2024-09-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreHotel', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='hoteles')),
                ('habitaciones', models.IntegerField()),
                ('habitacionesDIS', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('calle', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('numero_habitacion', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteleria.Cliente')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteleria.Hoteles')),
            ],
        ),
    ]
