"""
Django settings for aereopuerto project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as mensajes_de_error

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z$f(gply&i00ft4*aul!!lk=5ybm^$ugdwn^&n@st!m#cfm#92'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['renta-peliculas.fly.dev','localhost','127.0.0.1']
CSRF_TRUSTED_ORIGINS = ["https://renta-peliculas.fly.dev"]

# CAMBIO DE FORMATO DE FECHA PARA QUE COINCIDA CON EL INPUT DE FECHA DEL HTML VUELOS (debo modificar el formato de la fecha del html para que coincida con el de djnago)
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_vuelos', #registrar la aplicacion cada vez que se cree una
    'hoteleria', #segunda app para hoteles
    'blog',#tercera app blog
    'tienda', #cuarta app tienda
	'carro',
    'autentificacion',#logins
    'crispy_forms', #app instalada para dar formato a los formularios django
    'inicio', #app principal para home y contacto
    'pedidos', #registrar pedidos de la app tienda
    'whitenoise.runserver_nostatic', #app para los archivos staticos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'aereopuerto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['C:/Users/moises.ramirezr/Documents/curso-django/aereopuerto/aereopuerto/TEMPLATES/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carro.context_processor.importe_total_carro',
            ],
        },
    },
]

WSGI_APPLICATION = 'aereopuerto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#usando postgress sql

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'agenciaviajes',
#        'USER': 'postgres',
#        'PASSWORD': '361852h17',
#        'HOST':'127.0.0.1',
#        'DATABASE_PORT':'5432',
       # 'OPTIONS' : {
       #     'options': '-c timezone=UTC'
       # },
#    }
#}
# usando sqllite3
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False # true usara la localizacion de la zona horaria, False evitara que ocupe localizacion

#USE_TZ = True 




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Asegúrate de que esta ruta sea correcta
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #para optimizar los archivos estaticos

#direccion de archivos multimedia que inserta django/admin
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media')


#envio de correo electronico
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.office365.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER="moises.ramirezr@fgr.org.mx"
EMAIL_HOST_PASSWORD="Et050941-MOraR"
DEFAULT_FROM_EMAIL = 'moises.ramirezr@fgr.org.mx'


CRISPY_TEMPLATE_PACK="bootstrap4"

MESSAGE_TAGS={
    mensajes_de_error.DEBUG:'debug',
    mensajes_de_error.INFO:'info',
    mensajes_de_error.SUCCESS:'success',
    mensajes_de_error.WARNING:'warning',
    mensajes_de_error.ERROR:'danger',
}
