# Generated by Django 3.2.25 on 2024-10-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
