# Generated by Django 3.2.25 on 2024-10-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20241007_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario_id',
            new_name='user',
        ),
    ]
