# Generated by Django 3.2.25 on 2024-10-10 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('apellidos', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=20)),
                ('partida', models.CharField(max_length=20, verbose_name='origen')),
                ('fechaSAL', models.DateField()),
                ('hora', models.TimeField()),
                ('asientosDis', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('descuento', models.IntegerField(default=0, help_text='Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('realizado', models.BooleanField(default='False')),
                ('fecha_llegada', models.DateField(default='2024-01-01')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
