# Generated by Django 2.2 on 2024-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('apellidos', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('realizado', models.BooleanField(default='False')),
                ('fecha_llegada', models.DateField(default='2024-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=20)),
                ('partida', models.CharField(max_length=20, verbose_name='origen')),
                ('fechaSAL', models.DateField()),
                ('hora', models.TimeField()),
                ('asientosDis', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
